[package]
name = "dakia"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
mini-redis = "0.4"
async-trait="0.1"
pingora = { version = "0.1", features = [ "lb" ] }