daemon: true
error_log: "/var/log/dakia/error.log"
pid_file: "/var/run/dakia.pid"
upgrade_sock: "/var/run/dakia.sock"
user: "dakia_user"
group: "dakia_group"
threads: 4
work_stealing: true
grace_period_seconds: 60
graceful_shutdown_timeout_seconds: 30
upstream_keepalive_pool_size: 10
upstream_connect_offload_threadpools: 2
upstream_connect_offload_thread_per_pool: 5
upstream_debug_ssl_keylog: false
router_config:
  gateways:
    - bind_addresses:
        - host: "0.0.0.0"
          port: 8080
        - host: "0.0.0.0"
          port: 80
      downstreams:
        - host: "w3worker.net"
        - host: "localhost"
      backends:
        - name: "payment"
          default: false
          traffic_distribution_policy:
            selection_algorithm: "RoundRobin"
          upstreams:
            - address:
                host: "0.0.0.0"
                port: 3000
              tls: false
              sni: null
              weight: 1
            - address:
                host: "0.0.0.0"
                port: 3001
              tls: false
              sni: null
              weight: 2
        - name: "search"
          default: false
          upstreams:
            - address:
                host: "0.0.0.0"
                port: 3002
              tls: false
              sni: null
        - name: "content"
          default: true
          upstreams:
            - address:
                host: "0.0.0.0"
                port: 3003
              tls: false
              sni: null
      routes:
        - pattern: "*/pay"
          pattern_type: "Wildcard"
          backend: "payment"
        - pattern: "*/query"
          pattern_type: "Wildcard"
          backend: "payment"
        - pattern: "*"
          pattern_type: "Wildcard"
          backend: "content"
